language: objective-c
osx_image: xcode11
xcode_workspace: TravisTest.xcworkspace
xcode_scheme: TravisTest
xcode_destination: platform=iOS Simulator, OS=12.4, name=iPhone 11
before_install:
- gem install cocoapods-acknowledgements
- gem install cocoapods
- pod update
script:
- set -o pipefail
- travis_retry xcodebuild -workspace TravisTest.xcworkspace -scheme TravisTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
